version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      GUNICORN_ACCESS_LOGFILE: /dev/null
    logging:
      driver: "none"

  api:
    build:
      context: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    env_file:
      - .env
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}
    depends_on:
      - api
    command: npm run dev

volumes:
  postgres-data: