version: '3.9'

services:
  db:
    image: postgres
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/amd64
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      GUNICORN_ACCESS_LOGFILE: /dev/null
    logging:
      driver: "none"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      NODE_ENV: production
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - ${FRONTEND_PORT}:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    depends_on:
      - api
    restart: always

volumes:
  postgres-data: